### ISSUE TITLE
[TASK] WebAssembly support for non-protocol Gadget members

### ISSUE THREAD

**Issue by Tjemmmic** [webb-tools/gadget#114]
## Task Overview
Gadget should be capable of being built to WebAssembly for use in a browser. Each individual package/member should be capable of both Native and WASM builds.

Many of the features/functionalities in the goals below were addressed in PR #128. This PR was merged prior to all goals being met because of large-scale restructuring occurring in the Gadget repo. The remaining points are to be addressed in PR #___.
- - - 

### gadget-core
   - [x] Builds to wasm32-unknown-unknown target (Compiles as WASM lib)
   - [x] Successfully runs in Web

### protocols-macro
   - [x] Builds to wasm32-unknown-unknown target (Compiles as WASM lib)
   - [x] Successfully runs in Web

### gadget-common
   - [x] Builds to wasm32-unknown-unknown target (Compiles as WASM lib)
   - [x] Successfully runs in Web 

### gadget-io
   - [x] Manages differences in shell between Native and WASM targets
   - [x] Manages differences in keystore between Native and WASM targets
   - [x] Builds to wasm32-unknown-unknown target (Compiles as WASM lib)
   - [x] Successfully runs in Web 

### shell-sdk
   - [x] Builds to wasm32-unknown-unknown target (Compiles as WASM lib)
   - [x] Utilizes WASM version of Tokio functionalities - tasks, timing, etc.
   - [x] Read and write shell information between RustWASM and TypeScript
   - [x] Runs in Web - _Without fully functioning Networking_

### shell-sdk
   - [ ] WebRTC Networking that supports Private-to-Private
   - [ ] Successfully executes jobs(V1) or services(v2) on a Tangle Network

### Web Tests - All tests for a package in Web Browser (wasm-pack test --{browser-name})
   - [ ] gadget-core
   - [ ] gadget-common
   - [ ] gadget-io
   - [ ] protocols-macro
   - [ ] shell

**Comment by drewstone** [comment]
Why do we need test-utils in wasm?
