### ISSUE TITLE
[TASK] WASM support for zcash-frost

### ISSUE THREAD

**Issue by Tjemmmic** [webb-tools/gadget#118]
### Task Overview
The protocol should function for both native and WASM gadget builds. Tests should be implemented to ensure all functionalities work consistently across build targets. As mentioned in the parent Checklist #106, Gadget must be able to connect to the Tangle network - tests with a Tangle testnet should be done to ensure this works.
- - -

### Checklist
- [x] Builds to WASM
- [ ] Runs in Browser
- [ ] Implement Web Tests
- [ ] Tangle Testnet Tests

**Comment by Tjemmmic** [comment]
Moved to https://github.com/webb-tools/protocols/issues/6
