### ISSUE TITLE
[CHECKLIST] Shell: Dynamic Protocol Loading

### ISSUE THREAD

**Issue by tbraun96** [webb-tools/gadget#124]
In order to allow easy interoperability with external (and internal) protocols, we need a way for the shell to load protocols at runtime that may or may not be internal (i.e., the "internal" protocols are the protocols inside this repo, "external" protocols are protocols outside this repo). To do this, we can add logic to the Shell to read a global config file (GCF) located in the tangle repo that contains a list of roles and their corresponding repository and Git revision. The shell will then query the blockchain to get the active roles, then, for each role, perform a lookup in GCF for the repository to fetch the contents and checkout the verified revision. By doing this, external developers can add in their own protocols, then, open a PR in tangle to add an entry to their repo in the GCF, as well as any related signature verification code. An example GCF:

```toml
[protocols.dkls]
role_enum = "Dkls" # or whatever its variant value is in the RoleType
repository = "https://github.com/webb-tools/silent-shard-dkls23-gadget"
rev = "7559575b0f8d96dbf2dd86f22567179f2fc31d3c"
binary-name = "silent-shard-dkls23-ll-protocol"

[protocols.bls]
role_enum = "GennaroDkg"
...
```

Since we want a standardized format and development experience for adding and working with protocols, we should convert all internal protocols into external protocols.

The next part to discuss is how to execute the code once downloaded. We can locally compile the code, or, we can have precompiled artifacts. Supposing we decide to compile the code, we need a standardized methodology. To do this, each compiled repository should generate a binary output using the corresponding `binary-name` entry in the GCF: `cargo run --release --bin binary-name`

Next, each `protocol.rs`'s `run` function requires these inputs:

* blockchain_client
* pallet_tx
* network
* logger
* account_id
* keystore
* prometheus_config

These values will need to be created *inside* the protocol repo itself, we can provide an SDK to do this for them. Thus, each protocol will be a standalone binary running as a child process of the original shell (we can now call the "original shell" "Shell Manager"). The Shell Manager's only duty is to find relevant roles, and then fetch and execute the corresponding code for the roles. Since we require a rev in the GCF, which is implicitly hashed, external users cannot introduce malicious code by simply pushing to main; we will have to validate external code ourselves.

The tasklist thus boils down to this:

- [x] Create a GCF in the gadget repo
- [x] Spec: Determine if we should standardize precompiles or compile code on the fly
- [x] Convert the shell into a Shell Manager
- [x] Create an SDK for protocol use that is referenced from inside the protocol repo as a dependency
- [x] Convert existing internal protocols into external protocols, add to GCF

**Comment by drewstone** [comment]
The gadgets as they currently are should already be "external" in the sense that I wouldn't see the need to modify their interface/spec. But yes we need the shell to treat them as such, which would mean the burden of work is on the shell.

**Comment by drewstone** [comment]
Please share what you have in mind otherwise.. what changes would be required to go from internal to external? What would the notion of precompiles entail.. always existing gadgets in the shell?

**Comment by drewstone** [comment]
Repo https://github.com/webb-tools/protocol-template
