### ISSUE TITLE
[CHECKLIST] Gadget CLI

### ISSUE THREAD

**Issue by drewstone** [webb-tools/gadget#147]
# Overview
The gadget CLI should enable a quick and easy developer experience for creating, testing, and deploying gadget protocols as Tangle Service Blueprints.
- Be able to write a blueprint and deploy it on chain (`gadget blueprint create`, `gadget blueprint deploy`)
- Create a service request for that blueprint and select the configuration onchain. (Polkadot Apps, execute the extrinsic)
- Have the participants involved execute that service. (run the service, submit results to the chain).

## Checklist
- [x] https://github.com/webb-tools/gadget/issues/148
- [x] https://github.com/webb-tools/gadget/issues/149
- [x] https://github.com/webb-tools/gadget/issues/150
- [x] https://github.com/webb-tools/blueprint-template/issues/2
- [x] #225
- [x] #226

![image](https://github.com/webb-tools/tangle/assets/13153687/dc744d48-0318-4dcc-b1b6-3f42327c9b23)
