### ISSUE TITLE
[CHECKLIST] Eigenlayer Blueprint Integration

### ISSUE THREAD

**Issue by Tjemmmic** [webb-tools/gadget#232]
# [CHECKLIST] Integration of Eigenlayer into Gadget Blueprints
## Summary
Eigenlayer should be supported by Gadget, so that a developer could choose to build with Eigenlayer in mind as a Gadget's context. For example, when using the `gadget blueprint create` command, it should be possible to choose to build for Eigenlayer, where the following will happen:
- The user can choose whether to start with an ECDSA (Hello World AVS) or BLS (Incredible Squaring AVS) Base
- Generic AVS structure will be automatically generated
- General Smart Contracts will be created based on the name of the AVS specified (i.e., GivenNameTaskManager.sol, GivenNameServiceManager.sol, IGivenNameTaskManager.sol)
- Proc Macros used to automatically generate code for handling Task Creation Subscriptions and Task Submissions

## Checklist

- [ ] [TASK] EL Blueprint Integration - Proc Macros `job` and `report`

- [ ] [TASK] EL Blueprint Integration - Add support to Gadget CLI

- [ ] [TASK] EL Blueprint Integration - AVS and Contract Structural Generation

- [ ] [TASK] EL Blueprint Integration - Simplified Developer Experience
